### ISSUE TITLE
YouTube support??

### ISSUE THREAD

**Issue by versean** [Team-Poolside/twitch-danmaku-overlay#1]
That would be really cool!

**Comment by HotelCalifornia** [comment]
it's doable in theory, though one of the nice things about the way twitch chat works as opposed to youtube is that you don't need an API key for it, so im not sure how id handle that. i guess it could be another url parameter....

**Comment by HotelCalifornia** [comment]
and actually moreover the youtube livestreaming API for chat messages requires (as far as i can tell) polling the server for new messages every so often, which is again in contrast with the twitch model of just being an IRC chatroom to which you can connect and be notified on new message. it's sufficiently different enough that i don't think im willing to put in the energy to support it (and frankly i was only planning on supporting this project in a limited fashion anyway). sorry!

pull requests are welcome though
